version: '3'
services:
    api:
      build:
        context: .
        dockerfile: Dockerfile-flask
      ports:
          - "5000:5000"
      volumes:
          - .:/code
    jenkins:
      build:
        context: .
        dockerfile: Dockerfile-jenkins
        
