version: '3'
services:
    dns-server:
      image: dvdarias/docker-hoster
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock
        - /etc/hosts:/tmp/hosts
    api:
      build:
        context: .
        dockerfile: Dockerfile-flask
      ports:
          - "5000:5000"
      volumes:
          - .:/code
    jenkins:
      image: jenkins/jenkins:lts
      build:
        context: .
        dockerfile: Dockerfile-jenkins      
      ports:
        - "8080:8080"        
      volumes: 
        - ./jenkins_home:/var/jenkins_home
        - ./jenkins_home/plugins:/usr/share/jenkins/ref/plugins
        - ./jenkins_home/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      